# dist: trusty
# sudo: required
sudo: false

language: python
python:
  - 3.5
  - 3.6-dev
#  - 3.7

addons:
  apt:
    packages:
    - ldap-utils
    - slapd
    - freeradius

before_script:
  - mkdir /tmp/slapd
  - slapd -f tests/resources/slapd.conf -h "ldap://0.0.0.0:3389" &
  - sleep 3
  - ldapadd -x -H ldap://localhost:3389 -D cn=admin,dc=example,dc=com -w test -f tests/resources/01_setup_nodes.ldif
  - ldapadd -x -H ldap://localhost:3389 -D cn=admin,cn=config         -w test -f tests/resources/02_enable_memberof.ldif
  - ldapadd -x -H ldap://localhost:3389 -D cn=admin,dc=example,dc=com -w test -f tests/resources/03_add_user.ldif
  - ldapadd -x -H ldap://localhost:3389 -D cn=admin,dc=example,dc=com -w test -f tests/resources/04_add_group.ldif
#  - echo -e '"vaulttest"     Cleartext-Password := "test1234"\n               Reply-Message = "Hello, %{User-Name}"' | sudo tee -a /etc/freeradius/users
#  - sudo service freeradius restart
#  - sudo radtest 'vaulttest' test1234 localhost 0 testing123

install: pip install -U tox-travis

script: tox

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: terrycain
  password:
    secure: R9UvpiT9OFvwaMb9IFdC2OX98t+X81DMLDJE0u0DeShJqtll5Voa81RfULeo+V7afqYNA7aFP7qitGjaUDXIGQ2FghgbYO7w2doDOI2jSDa+VNSckCrdoaCigJ/C8QkFGvkt5g21zL1gkQhxWXJGLCudGYEKT9OBPM/Q/ce4SF3DSF1cdRb3SIPuVeV4/GW/dquqG3Tfxm2wDKi96BCy7259fNwKNL0wj6ENaD4+A50IQfOo9vE9ul0JZJvpS4H2vs3yeegXuuMJuOCtmdc6qDmDjj2nFzBiF53E/E88Y4D99v81klJrW59TnrTqEs+e6twDG7ind+vRRGoX4bes5MSRUnhayyz23mIRmh/NQCYlXbS1m53aG31GJfn6JbkXGrzCgjZ9B3bioWDMvvGMLjRGRkKUSuPQF9MaBbWQElT3Fw3+v7FNrVo40yHO5+QrCTgKPoyQ12Hdse9d/omx0RgnBz10pHGgNo+A+WT/Ix4EM4IctELqfz1yYsp0kcO7AfT5wH9tOfwMZaNs5lkkK2ePpcqowl3sdAzkN6IBkkHZirCtLRtHz8wgMZa/pj6i4vBClH1hfXiwSmaDIqgPgXOzb+jP4kuofEROZ2+Pyjhi7vZj8wnehBewO8qsMp17D9fRJrtf9uofCXFvMN1spFZWKueS4pnQuyoHbtM8M6U=
  on:
    tags: true
    repo: terrycain/aiovault
    python: 3.6-dev
